#!/usr/bin/env sh

STAGED_TS_FILES=$(git diff --cached --name-only --diff-filter=ACMR | rg '^src/.*\.ts$' || true)

if [ -z "$STAGED_TS_FILES" ]; then
  exit 0
fi

printf '%s\n' "$STAGED_TS_FILES" | xargs npx prettier --write
printf '%s\n' "$STAGED_TS_FILES" | xargs git add
